### ISSUE TITLE
LIBRO-MGMT-003 - Historias de Usuario

### ISSUE THREAD

**Issue by JuanPSuarez** [ISPC-Bookster/Libroteka#3]
Plantear Historias de Usuarios en base a los requerimientos del proyecto teniendo en cuenta una redacción y nomenclatura adecuada, ej “#US01 Como usuario quiero registrarme en el sitio web para comprar uno o varios productos” y su respectivos criterios de aceptación. Pueden utilizar la siguiente plantilla: [Plantilla Historias de Usuario](https://docs.google.com/spreadsheets/d/13qx2aip_ppAD6lnJ7LfJ_foLKpADqb72/edit?usp=sharing&ouid=117977189208786225858&rtpof=true&sd=true)

**Comment by JuanPSuarez** [comment]
https://github.com/ISPC-Bookster/Libroteka/wiki/Historias-de-Usuario

**Comment by pupaycleo** [comment]
Modifique Las HU N° 6 , 8 y 12
